## Install Kaggle API

In [1]:
%pip install kagglehub

Requirement already satisfied: kagglehub in ./capstone/lib/python3.13/site-packages (0.3.13)
Requirement already satisfied: packaging in ./capstone/lib/python3.13/site-packages (from kagglehub) (25.0)
Requirement already satisfied: pyyaml in ./capstone/lib/python3.13/site-packages (from kagglehub) (6.0.3)
Requirement already satisfied: requests in ./capstone/lib/python3.13/site-packages (from kagglehub) (2.32.5)
Requirement already satisfied: tqdm in ./capstone/lib/python3.13/site-packages (from kagglehub) (4.67.1)
Requirement already satisfied: charset_normalizer<4,>=2 in ./capstone/lib/python3.13/site-packages (from requests->kagglehub) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in ./capstone/lib/python3.13/site-packages (from requests->kagglehub) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./capstone/lib/python3.13/site-packages (from requests->kagglehub) (2.6.0)
Requirement already satisfied: certifi>=2017.4.17 in ./capstone/lib/python3.13/site-packages (from requests->kagglehub) (2025.11.12)

[notice] A new release of pip is available: 24.3.1 -> 25.3
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

## Download Kaggle dataset

In [2]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("wordsforthewise/lending-club")

print("Path to dataset files:", path)

/Users/priscillaashleywijaya/Desktop/General/NUS Fintech Society/capstone/src/capstone/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Path to dataset files: /Users/priscillaashleywijaya/.cache/kagglehub/datasets/wordsforthewise/lending-club/versions/3

## Requirements

In [3]:
import re
import os

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', '{:.2f}'.format)

# "magic" command to make plots show up in the notebook
%matplotlib inline

# Data analysis

In [4]:
folders = os.listdir(path)
# Skip .xslx file, if we are ever able to upload it...
# Currently can't upload due to conflicts with other versions of the dataset on Kaggle.
folders = [f for f in folders if 'xlsx' not in f]
folders

['rejected_2007_to_2018q4.csv',
 'accepted_2007_to_2018q4.csv',
 'rejected_2007_to_2018Q4.csv.gz',
 'accepted_2007_to_2018Q4.csv.gz']

In [5]:
os.listdir(path + "/" + folders[1])

['accepted_2007_to_2018Q4.csv']

In [6]:
acc_folder = path + "/" + [f for f in folders if 'accepted' in f][0]
accepted_fn = acc_folder + '/' + os.listdir(acc_folder)[0]

rej_folder = path + "/" + [f for f in folders if 'rejected' in f][0]
rejected_fn = rej_folder + '/' + os.listdir(rej_folder)[0]

accepted_fn

'/Users/priscillaashleywijaya/.cache/kagglehub/datasets/wordsforthewise/lending-club/versions/3/accepted_2007_to_2018q4.csv/accepted_2007_to_2018Q4.csv'

In [7]:
# check if the actual file is still there
if os.path.isfile(accepted_fn) and os.path.isfile(rejected_fn):
    print('both paths point to the actual file')
else:
    print('locate files manually')

both paths point to the actual file

In [8]:
# reading the csv
acc_df = pd.read_csv(accepted_fn)
rej_df = pd.read_csv(rejected_fn)

/var/folders/tg/g161x0m50lxgx68hfwk_3qk80000gn/T/ipykernel_71924/578552646.py:2: DtypeWarning: Columns (0,19,49,59,118,129,130,131,134,135,136,139,145,146,147) have mixed types. Specify dtype option on import or set low_memory=False.
  acc_df = pd.read_csv(accepted_fn)

In [9]:
acc_df.shape

(2260701, 151)

2260701 rows, 151 columns in accepted file

In [10]:
rej_df.shape

(27648741, 9)

27648741 rows, 9 columns in accepted file

### FICO Score
- FICO stands for Fair Isaac Corporation, the company that created one of the most widely used credit scoring systems in the United States.

- A FICO score is a numerical measure of a person's creditworthiness — basically, how likely they are to repay a loan.

In [11]:
# fico score in accepted loans
[col for col in acc_df.columns if 'fico' in col.lower()]

['fico_range_low',
 'fico_range_high',
 'last_fico_range_high',
 'last_fico_range_low',
 'sec_app_fico_range_low',
 'sec_app_fico_range_high']

In [12]:
# fico score in rejected loans
[col for col in rej_df.columns if 'fico' in col.lower()]

[]

### Rejected information

In [13]:
rej_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27648741 entries, 0 to 27648740
Data columns (total 9 columns):
 #   Column                Dtype
---  ------                -----
 0   Amount Requested      float64
 1   Application Date      object
 2   Loan Title            object
 3   Risk_Score            float64
 4   Debt-To-Income Ratio  object
 5   Zip Code              object
 6   State                 object
 7   Employment Length     object
 8   Policy Code           float64
dtypes: float64(3), object(6)
memory usage: 1.9+ GB

## Accepted information

In [14]:
acc_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2260701 entries, 0 to 2260700
Columns: 151 entries, id to settlement_term
dtypes: float64(113), object(38)
memory usage: 2.5+ GB

In [15]:
pd.options.display.max_rows

In [16]:
acc_df.columns

Index(['id', 'member_id', 'loan_amnt', 'funded_amnt', 'funded_amnt_inv',
       'term', 'int_rate', 'installment', 'grade', 'sub_grade',
       ...
       'hardship_payoff_balance_amount', 'hardship_last_payment_amount',
       'disbursement_method', 'debt_settlement_flag',
       'debt_settlement_flag_date', 'settlement_status', 'settlement_date',
       'settlement_amount', 'settlement_percentage', 'settlement_term'],
      dtype='object', length=151)

In [17]:
acc_df.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,fico_range_low,fico_range_high,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,last_fico_range_high,last_fico_range_low,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_fico_range_low,sec_app_fico_range_high,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,68407277,NaN,3600.00,3600.00,3600.00,36 months,13.99,123.03,C,C4,leadman,10+ years,MORTGAGE,55000.00,Not Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,debt_consolidation,Debt consolidation,190xx,PA,5.91,0.00,Aug-2003,675.00,679.00,1.00,30.00,NaN,7.00,0.00,2765.00,29.70,13.00,w,0.00,0.00,4421.72,4421.72,3600.00,821.72,0.00,0.00,0.00,Jan-2019,122.67,NaN,Mar-2019,564.00,560.00,0.00,30.00,1.00,Individual,NaN,NaN,NaN,0.00,722.00,144904.00,2.00,2.00,0.00,1.00,21.00,4981.00,36.00,3.00,3.00,722.00,34.00,9300.00,3.00,1.00,4.00,4.00,20701.00,1506.00,37.20,0.00,0.00,148.00,128.00,3.00,3.00,1.00,4.00,69.00,4.00,69.00,2.00,2.00,4.00,2.00,5.00,3.00,4.00,9.00,4.00,7.00,0.00,0.00,0.00,3.00,76.90,0.00,0.00,0.00,178050.00,7746.00,2400.00,13734.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,68355089,NaN,24700.00,24700.00,24700.00,36 months,11.99,820.28,C,C1,Engineer,10+ years,MORTGAGE,65000.00,Not Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,small_business,Business,577xx,SD,16.06,1.00,Dec-1999,715.00,719.00,4.00,6.00,NaN,22.00,0.00,21470.00,19.20,38.00,w,0.00,0.00,25679.66,25679.66,24700.00,979.66,0.00,0.00,0.00,Jun-2016,926.35,NaN,Mar-2019,699.00,695.00,0.00,NaN,1.00,Individual,NaN,NaN,NaN,0.00,0.00,204396.00,1.00,1.00,0.00,1.00,19.00,18005.00,73.00,2.00,3.00,6472.00,29.00,111800.00,0.00,0.00,6.00,4.00,9733.00,57830.00,27.10,0.00,0.00,113.00,192.00,2.00,2.00,4.00,2.00,NaN,0.00,6.00,0.00,5.00,5.00,13.00,17.00,6.00,20.00,27.00,5.00,22.00,0.00,0.00,0.00,2.00,97.40,7.70,0.00,0.00,314017.00,39475.00,79300.00,24667.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,68341763,NaN,20000.00,20000.00,20000.00,60 months,10.78,432.66,B,B4,truck driver,10+ years,MORTGAGE,63000.00,Not Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,home_improvement,NaN,605xx,IL,10.78,0.00,Aug-2000,695.00,699.00,0.00,NaN,NaN,6.00,0.00,7869.00,56.20,18.00,w,0.00,0.00,22705.92,22705.92,20000.00,2705.92,0.00,0.00,0.00,Jun-2017,15813.30,NaN,Mar-2019,704.00,700.00,0.00,NaN,1.00,Joint App,71000.00,13.85,Not Verified,0.00,0.00,189699.00,0.00,1.00,0.00,4.00,19.00,10827.00,73.00,0.00,2.00,2081.00,65.00,14000.00,2.00,5.00,1.00,6.00,31617.00,2737.00,55.90,0.00,0.00,125.00,184.00,14.00,14.00,5.00,101.00,NaN,10.00,NaN,0.00,2.00,3.00,2.00,4.00,6.00,4.00,7.00,3.00,6.00,0.00,0.00,0.00,0.00,100.00,50.00,0.00,0.00,218418.00,18696.00,6200.00,14877.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,66310712,NaN,35000.00,35000.00,35000.00,60 months,14.85,829.90,C,C5,Information Systems Officer,10+ years,MORTGAGE,110000.00,Source Verified,Dec-2015,Current,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,debt_consolidation,Debt consolidation,076xx,NJ,17.06,0.00,Sep-2008,785.00,789.00,0.00,NaN,NaN,13.00,0.00,7802.00,11.60,17.00,w,15897.65,15897.65,31464.01,31464.01,19102.35,12361.66,0.00,0.00,0.00,Feb-2019,829.90,Apr-2019,Mar-2019,679.00,675.00,0.00,NaN,1.00,Individual,NaN,NaN,NaN,0.00,0.00,301500.00,1.00,1.00,0.00,1.00,23.00,12609.00,70.00,1.00,1.00,6987.00,45.00,67300.00,0.00,1.00,0.00,2.00,23192.00,54962.00,12.10,0.00,0.00,36.00,87.00,2.00,2.00,1.00,2.00,NaN,NaN,NaN,0.00,4.00,5.00,8.00,10.00,2.00,10.00,13.00,5.00,13.00,0.00,0.00,0.00,1.00,100.00,0.00,0.00,0.00,381215.00,52226.00,62500.00,18000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,68476807,NaN,10400.00,10400.00,10400.00,60 months,22.45,289.91,F,F1,Contract Specialist,3 years,MORTGAGE,104433.00,Source Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,major_purchase,Major purchase,174xx,PA,25.37,1.00,Jun-1998,695.00,699.00,3.00,12.00,NaN,12.00,0.00,21929.00,64.50,35.00,w,0.00,0.00,11740.50,11740.50,10400.00,1340.50,0.00,0.00,0.00,Jul-2016,10128.96,NaN,Mar-2018,704.00,700.00,0.00,NaN,1.00,Individual,NaN,NaN,NaN,0.00,0.00,331730.00,1.00,3.00,0.00,3.00,14.00,73839.00,84.00,4.00,7.00,9702.00,78.00,34000.00,2.00,1.00,3.00,10.00,27644.00,4567.00,77.50,0.00,0.00,128.00,210.00,4.00,4.00,6.00,4.00,12.00,1.00,12.00,0.00,4.00,6.00,5.00,9.00,10.00,7.00,19.00,6.00,12.00,0.00,0.00,0.00,4.00,96.60,60.00,0.00,0.00,439570.00,95768.00,20300.00,88097.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
acc_df.tail()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,fico_range_low,fico_range_high,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,last_fico_range_high,last_fico_range_low,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_fico_range_low,sec_app_fico_range_high,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
2260696,88985880,NaN,40000.00,40000.00,40000.00,60 months,10.49,859.56,B,B3,Vice President,9 years,MORTGAGE,227000.00,Verified,Oct-2016,Current,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,debt_consolidation,NaN,907xx,CA,12.75,7.00,Feb-1995,705.00,709.00,1.00,9.00,NaN,5.00,0.00,8633.00,64.90,37.00,f,23252.59,23252.59,24903.93,24903.93,16747.41,8156.52,0.00,0.00,0.00,Mar-2019,859.56,Apr-2019,Mar-2019,724.00,720.00,0.00,10.00,1.00,Individual,NaN,NaN,NaN,0.00,0.00,28398.00,0.00,2.00,0.00,1.00,15.00,19765.00,46.00,0.00,0.00,5141.00,51.00,13300.00,3.00,0.00,2.00,2.00,5680.00,4070.00,66.90,0.00,0.00,154.00,258.00,33.00,15.00,3.00,41.00,9.00,1.00,9.00,6.00,2.00,3.00,2.00,15.00,9.00,3.00,23.00,3.00,5.00,0.00,0.00,7.00,0.00,75.70,50.00,0.00,0.00,55970.00,28398.00,12300.00,42670.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260697,88224441,NaN,24000.00,24000.00,24000.00,60 months,14.49,564.56,C,C4,Program Manager,6 years,RENT,110000.00,Not Verified,Oct-2016,Charged Off,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,debt_consolidation,Debt consolidation,334xx,FL,18.30,0.00,Jul-1999,660.00,664.00,0.00,67.00,72.00,10.00,1.00,17641.00,68.10,31.00,f,0.00,0.00,6755.40,6755.40,3521.91,3233.49,0.00,0.00,0.00,Oct-2017,564.56,NaN,Mar-2019,594.00,590.00,0.00,67.00,1.00,Individual,NaN,NaN,NaN,0.00,0.00,62426.00,0.00,2.00,0.00,2.00,20.00,44785.00,78.00,1.00,5.00,6172.00,73.00,25900.00,0.00,0.00,1.00,7.00,6243.00,4660.00,77.50,0.00,0.00,132.00,206.00,9.00,9.00,2.00,9.00,NaN,9.00,NaN,1.00,5.00,7.00,5.00,15.00,4.00,8.00,24.00,7.00,10.00,0.00,0.00,0.00,1.00,96.20,40.00,1.00,0.00,84664.00,62426.00,20700.00,58764.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,Y,Mar-2019,ACTIVE,Mar-2019,10000.00,44.82,1.00
2260698,88215728,NaN,14000.00,14000.00,14000.00,60 months,14.49,329.33,C,C4,Customer Service Technician,10+ years,MORTGAGE,95000.00,Verified,Oct-2016,Current,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,debt_consolidation,NaN,770xx,TX,23.36,0.00,Jun-1996,660.00,664.00,1.00,37.00,NaN,8.00,0.00,7662.00,54.00,22.00,w,8456.12,8456.12,9621.25,9621.25,5543.88,4027.96,49.41,0.00,0.00,Mar-2019,329.33,Apr-2019,Mar-2019,669.00,665.00,0.00,37.00,1.00,Individual,NaN,NaN,NaN,0.00,0.00,143066.00,0.00,1.00,1.00,2.00,7.00,32071.00,94.00,0.00,1.00,4093.00,84.00,14200.00,3.00,1.00,2.00,3.00,17883.00,1838.00,80.70,0.00,0.00,149.00,243.00,22.00,7.00,1.00,75.00,39.00,6.00,37.00,4.00,3.00,3.00,4.00,12.00,3.00,5.00,17.00,3.00,8.00,0.00,0.00,0.00,1.00,81.80,50.00,0.00,0.00,163804.00,44215.00,9500.00,34169.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260699,Total amount funded in policy code 1: 1465324575,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2260700,Total amount funded in policy code 2: 521953170,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
acc_df.info(verbose = True, max_cols=None)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2260701 entries, 0 to 2260700
Data columns (total 151 columns):
 #    Column                                      Dtype
---   ------                                      -----
 0    id                                          object
 1    member_id                                   float64
 2    loan_amnt                                   float64
 3    funded_amnt                                 float64
 4    funded_amnt_inv                             float64
 5    term                                        object
 6    int_rate                                    float64
 7    installment                                 float64
 8    grade                                       object
 9    sub_grade                                   object
 10   emp_title                                   object
 11   emp_length                                  object
 12   home_ownership                              object
 13   annual_inc                                  float64
 14   verification_status                         object
 15   issue_d                                     object
 16   loan_status                                 object
 17   pymnt_plan                                  object
 18   url                                         object
 19   desc                                        object
 20   purpose                                     object
 21   title                                       object
 22   zip_code                                    object
 23   addr_state                                  object
 24   dti                                         float64
 25   delinq_2yrs                                 float64
 26   earliest_cr_line                            object
 27   fico_range_low                              float64
 28   fico_range_high                             float64
 29   inq_last_6mths                              float64
 30   mths_since_last_delinq                      float64
 31   mths_since_last_record                      float64
 32   open_acc                                    float64
 33   pub_rec                                     float64
 34   revol_bal                                   float64
 35   revol_util                                  float64
 36   total_acc                                   float64
 37   initial_list_status                         object
 38   out_prncp                                   float64
 39   out_prncp_inv                               float64
 40   total_pymnt                                 float64
 41   total_pymnt_inv                             float64
 42   total_rec_prncp                             float64
 43   total_rec_int                               float64
 44   total_rec_late_fee                          float64
 45   recoveries                                  float64
 46   collection_recovery_fee                     float64
 47   last_pymnt_d                                object
 48   last_pymnt_amnt                             float64
 49   next_pymnt_d                                object
 50   last_credit_pull_d                          object
 51   last_fico_range_high                        float64
 52   last_fico_range_low                         float64
 53   collections_12_mths_ex_med                  float64
 54   mths_since_last_major_derog                 float64
 55   policy_code                                 float64
 56   application_type                            object
 57   annual_inc_joint                            float64
 58   dti_joint                                   float64
 59   verification_status_joint                   object
 60   acc_now_delinq                              float64
 61   tot_coll_amt                                float64
 62   tot_cur_bal                                 float64
 63   open_acc_6m                                 float64
 64   open_act_il                                 float64
 65   open_il_12m                                 float64
 66   open_il_24m                                 float64
 67   mths_since_rcnt_il                          float64
 68   total_bal_il                                float64
 69   il_util                                     float64
 70   open_rv_12m                                 float64
 71   open_rv_24m                                 float64
 72   max_bal_bc                                  float64
 73   all_util                                    float64
 74   total_rev_hi_lim                            float64
 75   inq_fi                                      float64
 76   total_cu_tl                                 float64
 77   inq_last_12m                                float64
 78   acc_open_past_24mths                        float64
 79   avg_cur_bal                                 float64
 80   bc_open_to_buy                              float64
 81   bc_util                                     float64
 82   chargeoff_within_12_mths                    float64
 83   delinq_amnt                                 float64
 84   mo_sin_old_il_acct                          float64
 85   mo_sin_old_rev_tl_op                        float64
 86   mo_sin_rcnt_rev_tl_op                       float64
 87   mo_sin_rcnt_tl                              float64
 88   mort_acc                                    float64
 89   mths_since_recent_bc                        float64
 90   mths_since_recent_bc_dlq                    float64
 91   mths_since_recent_inq                       float64
 92   mths_since_recent_revol_delinq              float64
 93   num_accts_ever_120_pd                       float64
 94   num_actv_bc_tl                              float64
 95   num_actv_rev_tl                             float64
 96   num_bc_sats                                 float64
 97   num_bc_tl                                   float64
 98   num_il_tl                                   float64
 99   num_op_rev_tl                               float64
 100  num_rev_accts                               float64
 101  num_rev_tl_bal_gt_0                         float64
 102  num_sats                                    float64
 103  num_tl_120dpd_2m                            float64
 104  num_tl_30dpd                                float64
 105  num_tl_90g_dpd_24m                          float64
 106  num_tl_op_past_12m                          float64
 107  pct_tl_nvr_dlq                              float64
 108  percent_bc_gt_75                            float64
 109  pub_rec_bankruptcies                        float64
 110  tax_liens                                   float64
 111  tot_hi_cred_lim                             float64
 112  total_bal_ex_mort                           float64
 113  total_bc_limit                              float64
 114  total_il_high_credit_limit                  float64
 115  revol_bal_joint                             float64
 116  sec_app_fico_range_low                      float64
 117  sec_app_fico_range_high                     float64
 118  sec_app_earliest_cr_line                    object
 119  sec_app_inq_last_6mths                      float64
 120  sec_app_mort_acc                            float64
 121  sec_app_open_acc                            float64
 122  sec_app_revol_util                          float64
 123  sec_app_open_act_il                         float64
 124  sec_app_num_rev_accts                       float64
 125  sec_app_chargeoff_within_12_mths            float64
 126  sec_app_collections_12_mths_ex_med          float64
 127  sec_app_mths_since_last_major_derog         float64
 128  hardship_flag                               object
 129  hardship_type                               object
 130  hardship_reason                             object
 131  hardship_status                             object
 132  deferral_term                               float64
 133  hardship_amount                             float64
 134  hardship_start_date                         object
 135  hardship_end_date                           object
 136  payment_plan_start_date                     object
 137  hardship_length                             float64
 138  hardship_dpd                                float64
 139  hardship_loan_status                        object
 140  orig_projected_additional_accrued_interest  float64
 141  hardship_payoff_balance_amount              float64
 142  hardship_last_payment_amount                float64
 143  disbursement_method                         object
 144  debt_settlement_flag                        object
 145  debt_settlement_flag_date                   object
 146  settlement_status                           object
 147  settlement_date                             object
 148  settlement_amount                           float64
 149  settlement_percentage                       float64
 150  settlement_term                             float64
dtypes: float64(113), object(38)
memory usage: 2.5+ GB

In [20]:
acc_df.describe()

,member_id,loan_amnt,funded_amnt,funded_amnt_inv,int_rate,installment,annual_inc,dti,delinq_2yrs,fico_range_low,fico_range_high,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_amnt,last_fico_range_high,last_fico_range_low,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,annual_inc_joint,dti_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_fico_range_low,sec_app_fico_range_high,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,deferral_term,hardship_amount,hardship_length,hardship_dpd,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,settlement_amount,settlement_percentage,settlement_term
count,0.00,2260668.00,2260668.00,2260668.00,2260668.00,2260668.00,2260664.00,2258957.00,2260639.00,2260668.00,2260668.00,2260638.00,1102166.00,359156.00,2260639.00,2260639.00,2260668.00,2258866.00,2260639.00,2260668.00,2260668.00,2260668.00,2260668.00,2260668.00,2260668.00,2260668.00,2260668.00,2260668.00,2260668.00,2260668.00,2260668.00,2260523.00,580775.00,2260668.00,120710.00,120706.00,2260639.00,2190392.00,2190392.00,1394538.00,1394539.00,1394539.00,1394539.00,1350744.00,1394539.00,1191818.00,1394539.00,1394539.00,1394539.00,1394320.00,2190392.00,1394539.00,1394538.00,1394538.00,2210638.00,2190322.00,2185733.00,2184597.00,2260523.00,2260639.00,2121597.00,2190391.00,2190391.00,2190392.00,2210638.00,2187256.00,519701.00,1965233.00,740359.00,2190392.00,2190392.00,2190392.00,2202078.00,2190392.00,2190392.00,2190392.00,2190391.00,2190392.00,2202078.00,2107011.00,2190392.00,2190392.00,2190392.00,2190237.00,2185289.00,2259303.00,2260563.00,2190392.00,2210638.00,2210638.00,2190392.00,108020.00,108021.00,108021.00,108021.00,108021.00,108021.00,106184.00,108021.00,108021.00,108021.00,108021.00,35942.00,10917.00,10917.00,10917.00,10917.00,8651.00,10917.00,10917.00,34246.00,34246.00,34246.00
mean,NaN,15046.93,15041.66,15023.44,13.09,445.81,77992.43,18.82,0.31,698.59,702.59,0.58,34.54,72.31,11.61,0.20,16658.46,50.34,24.16,4206.89,4205.97,12082.56,12064.39,9505.77,2431.39,1.52,143.88,23.98,3429.35,687.66,675.54,0.02,44.16,1.00,123624.64,19.25,0.00,232.73,142492.20,0.93,2.78,0.68,1.56,21.22,35506.65,69.14,1.29,2.75,5806.39,57.03,34573.94,1.01,1.48,2.04,4.52,13547.80,11394.26,57.90,0.01,12.37,125.74,181.49,14.02,8.30,1.56,24.84,39.30,7.02,35.78,0.50,3.68,5.63,4.77,7.73,8.41,8.25,14.00,5.58,11.63,0.00,0.00,0.08,2.08,94.11,42.44,0.13,0.05,178242.75,51022.94,23193.77,43732.01,33617.28,669.76,673.76,0.63,1.54,11.47,58.17,3.01,12.53,0.05,0.08,36.94,3.00,155.05,3.00,13.74,454.80,11636.88,193.99,5010.66,47.78,13.19
std,NaN,9190.25,9188.41,9192.33,4.83,267.17,112696.20,14.18,0.87,33.01,33.01,0.89,21.90,26.46,5.64,0.57,22948.31,24.71,11.99,7343.24,7342.33,9901.38,9896.99,8321.85,2679.74,11.84,748.16,131.23,6018.25,72.97,111.10,0.15,21.53,0.00,74161.35,7.82,0.07,8518.46,160692.64,1.14,3.00,0.93,1.58,26.05,44097.46,23.75,1.51,2.60,5690.56,20.90,36728.50,1.49,2.67,2.38,3.16,16474.08,16599.53,28.58,0.10,726.46,53.38,97.12,17.53,9.21,1.90,32.32,22.62,5.97,22.31,1.35,2.32,3.38,3.04,4.70,7.36,4.68,8.04,3.29,5.64,0.03,0.06,0.49,1.83,9.04,36.22,0.36,0.38,181574.81,49911.24,23006.56,45072.98,28153.87,44.73,44.73,0.99,1.76,6.63,25.55,3.28,8.15,0.41,0.41,23.92,0.00,129.04,0.00,9.67,375.39,7625.99,198.63,3693.12,7.31,8.16
min,NaN,500.00,500.00,0.00,5.31,4.93,0.00,-1.00,0.00,610.00,614.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00,-0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1.00,5693.51,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,540.00,544.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,3.00,0.64,3.00,0.00,1.92,55.73,0.01,44.21,0.20,0.00
25%,NaN,8000.00,8000.00,8000.00,9.49,251.65,46000.00,11.89,0.00,675.00,679.00,0.00,16.00,55.00,8.00,0.00,5950.00,31.50,15.00,0.00,0.00,4546.46,4531.80,3000.00,728.19,0.00,0.00,0.00,310.33,654.00,650.00,0.00,27.00,1.00,83400.00,13.53,0.00,0.00,29092.00,0.00,1.00,0.00,0.00,7.00,8695.00,55.00,0.00,1.00,2284.00,43.00,14700.00,0.00,0.00,0.00,2.00,3080.00,1722.00,35.40,0.00,0.00,96.00,116.00,4.00,3.00,0.00,6.00,21.00,2.00,17.00,0.00,2.00,3.00,3.00,4.00,3.00,5.00,8.00,3.00,8.00,0.00,0.00,0.00,1.00,91.30,0.00,0.00,0.00,50731.00,20892.00,8300.00,15000.00,15106.75,645.00,649.00,0.00,0.00,7.00,39.80,1.00,7.00,0.00,0.00,16.00,3.00,59.44,3.00,5.00,175.23,5627.00,44.44,2208.00,45.00,6.00
50%,NaN,12900.00,12875.00,12800.00,12.62,377.99,65000.00,17.84,0.00,690.00,694.00,0.00,31.00,74.00,11.00,0.00,11324.00,50.30,22.00,0.00,0.00,9329.72,9309.67,7000.00,1525.94,0.00,0.00,0.00,600.57,699.00,695.00,0.00,44.00,1.00,110000.00,18.84,0.00,0.00,79240.00,1.00,2.00,0.00,1.00,13.00,23127.00,72.00,1.00,2.00,4413.00,58.00,25400.00,1.00,0.00,1.00,4.00,7335.00,5442.00,60.20,0.00,0.00,130.00,164.00,8.00,6.00,1.00,14.00,37.00,5.00,33.00,0.00,3.00,5.00,4.00,7.00,6.00,7.00,12.00,5.00,11.00,0.00,0.00,0.00,2.00,100.00,37.50,0.00,0.00,114298.50,37864.00,16300.00,32696.00,26516.50,670.00,674.00,0.00,1.00,10.00,60.20,2.00,11.00,0.00,0.00,36.00,3.00,119.14,3.00,15.00,352.77,10028.39,133.16,4146.11,45.00,14.00
75%,NaN,20000.00,20000.00,20000.00,15.99,593.32,93000.00,24.49,0.00,715.00,719.00,1.00,50.00,92.00,14.00,0.00,20246.00,69.40,31.00,6149.94,6146.31,16940.87,16916.71,13899.10,3108.06,0.00,0.00,0.00,3743.75,734.00,730.00,0.00,62.00,1.00,147995.00,24.62,0.00,0.00,213204.00,1.00,3.00,1.00,2.00,24.00,46095.00,86.00,2.00,4.00,7598.00,72.00,43200.00,1.00,2.00,3.00,6.00,18783.00,14187.00,83.10,0.00,0.00,154.00,232.00,17.00,11.00,3.00,30.00,57.00,11.00,51.00,0.00,5.00,7.00,6.00,10.00,11.00,10.00,18.00,7.00,14.00,0.00,0.00,0.00,3.00,100.00,71.40,0.00,0.00,257755.00,64350.00,30300.00,58804.25,43769.00,695.00,699.00,1.00,2.00,15.00,78.60,4.00,17.00,0.00,0.00,56.00,3.00,213.26,3.00,22.00,620.17,16151.89,284.19,6850.17,50.00,18.00
max,NaN,40000.00,40000.00,40000.00,30.99,1719.83,110000000.00,999.00,58.00,845.00,850.00,33.00,226.00,129.00,101.00,86.00,2904836.00,892.30,176.00,40000.00,40000.00,63296.88,63296.88,40000.00,28192.50,1484.34,39859.55,7174.72,42192.05,850.00,845.00,20.00,226.00,1.00,7874821.00,69.49,14.00,9152545.00,9971659.00,18.00,57.00,25.00,51.00,511.00,1837038.00,1000.00,28.00,60.00,1170668.00,239.00,9999999.00,48.00,111.00,67.00,64.00,958084.00,711140.00,339.60,10.00,249925.00,999.00,999.00,547.00,382.00,94.00,661.00,202.00,25.00,202.00,58.00,50.00,72.00,71.00,86.00,159.00,91.00,151.00,65.00,101.00,7.00,4.00,58.00,32.00,100.00,100.00,12.00,85.00,9999999.00,3408095.00,1569000.00,2118996.00,1110019.00,845.00,850.00,6.00,27.00,82.00,434.30,43.00,106.00,21.00,23.00,185.00,3.00,943.94,3.00,37.00,2680.89,40306.41,1407.86,33601.00,521.35,181.00

## Data Cleaning

In [21]:
# 1. Get the list of column names
column_list = acc_df.columns.tolist()

# 2. Iterate and print each column name on a new line
for col in column_list:
    print(col)

id
member_id
loan_amnt
funded_amnt
funded_amnt_inv
term
int_rate
installment
grade
sub_grade
emp_title
emp_length
home_ownership
annual_inc
verification_status
issue_d
loan_status
pymnt_plan
url
desc
purpose
title
zip_code
addr_state
dti
delinq_2yrs
earliest_cr_line
fico_range_low
fico_range_high
inq_last_6mths
mths_since_last_delinq
mths_since_last_record
open_acc
pub_rec
revol_bal
revol_util
total_acc
initial_list_status
out_prncp
out_prncp_inv
total_pymnt
total_pymnt_inv
total_rec_prncp
total_rec_int
total_rec_late_fee
recoveries
collection_recovery_fee
last_pymnt_d
last_pymnt_amnt
next_pymnt_d
last_credit_pull_d
last_fico_range_high
last_fico_range_low
collections_12_mths_ex_med
mths_since_last_major_derog
policy_code
application_type
annual_inc_joint
dti_joint
verification_status_joint
acc_now_delinq
tot_coll_amt
tot_cur_bal
open_acc_6m
open_act_il
open_il_12m
open_il_24m
mths_since_rcnt_il
total_bal_il
il_util
open_rv_12m
open_rv_24m
max_bal_bc
all_util
total_rev_hi_lim
inq_fi
total_cu_tl
inq_last_12m
acc_open_past_24mths
avg_cur_bal
bc_open_to_buy
bc_util
chargeoff_within_12_mths
delinq_amnt
mo_sin_old_il_acct
mo_sin_old_rev_tl_op
mo_sin_rcnt_rev_tl_op
mo_sin_rcnt_tl
mort_acc
mths_since_recent_bc
mths_since_recent_bc_dlq
mths_since_recent_inq
mths_since_recent_revol_delinq
num_accts_ever_120_pd
num_actv_bc_tl
num_actv_rev_tl
num_bc_sats
num_bc_tl
num_il_tl
num_op_rev_tl
num_rev_accts
num_rev_tl_bal_gt_0
num_sats
num_tl_120dpd_2m
num_tl_30dpd
num_tl_90g_dpd_24m
num_tl_op_past_12m
pct_tl_nvr_dlq
percent_bc_gt_75
pub_rec_bankruptcies
tax_liens
tot_hi_cred_lim
total_bal_ex_mort
total_bc_limit
total_il_high_credit_limit
revol_bal_joint
sec_app_fico_range_low
sec_app_fico_range_high
sec_app_earliest_cr_line
sec_app_inq_last_6mths
sec_app_mort_acc
sec_app_open_acc
sec_app_revol_util
sec_app_open_act_il
sec_app_num_rev_accts
sec_app_chargeoff_within_12_mths
sec_app_collections_12_mths_ex_med
sec_app_mths_since_last_major_derog
hardship_flag
hardship_type
hardship_reason
hardship_status
deferral_term
hardship_amount
hardship_start_date
hardship_end_date
payment_plan_start_date
hardship_length
hardship_dpd
hardship_loan_status
orig_projected_additional_accrued_interest
hardship_payoff_balance_amount
hardship_last_payment_amount
disbursement_method
debt_settlement_flag
debt_settlement_flag_date
settlement_status
settlement_date
settlement_amount
settlement_percentage
settlement_term

In [22]:
data = acc_df.sample(100_000, random_state=42)

In [23]:
data["loan_status"].value_counts(dropna = False)

loan_status
Fully Paid                                             47460
Current                                                38887
Charged Off                                            12034
Late (31-120 days)                                       969
In Grace Period                                          368
Late (16-30 days)                                        187
Does not meet the credit policy. Status:Fully Paid        60
Does not meet the credit policy. Status:Charged Off       31
NaN                                                        4
Name: count, dtype: int64

In [24]:
def map_status(s):
    if s in ["Fully Paid", "Current", "In Grace Period"]:
        return 1
    if s in ["Charged Off", "Late (31-120 days)", "Late (16-30 days)"]:
        return 0
    return np.nan

data["loan_status_binary"] = data["loan_status"].apply(map_status)
data = data.dropna(subset=["loan_status_binary"])
data["loan_status_binary"] = data["loan_status_binary"].astype(int)

In [25]:
data.shape

(99905, 152)

In [26]:
data['loan_status_binary'].value_counts(normalize=True, dropna=False)

loan_status_binary
1   0.87
0   0.13
Name: proportion, dtype: float64

### Retain only columns that do not leak & are known at point of application

In [27]:
print(sorted(data.columns))

['acc_now_delinq', 'acc_open_past_24mths', 'addr_state', 'all_util', 'annual_inc', 'annual_inc_joint', 'application_type', 'avg_cur_bal', 'bc_open_to_buy', 'bc_util', 'chargeoff_within_12_mths', 'collection_recovery_fee', 'collections_12_mths_ex_med', 'debt_settlement_flag', 'debt_settlement_flag_date', 'deferral_term', 'delinq_2yrs', 'delinq_amnt', 'desc', 'disbursement_method', 'dti', 'dti_joint', 'earliest_cr_line', 'emp_length', 'emp_title', 'fico_range_high', 'fico_range_low', 'funded_amnt', 'funded_amnt_inv', 'grade', 'hardship_amount', 'hardship_dpd', 'hardship_end_date', 'hardship_flag', 'hardship_last_payment_amount', 'hardship_length', 'hardship_loan_status', 'hardship_payoff_balance_amount', 'hardship_reason', 'hardship_start_date', 'hardship_status', 'hardship_type', 'home_ownership', 'id', 'il_util', 'initial_list_status', 'inq_fi', 'inq_last_12m', 'inq_last_6mths', 'installment', 'int_rate', 'issue_d', 'last_credit_pull_d', 'last_fico_range_high', 'last_fico_range_low', 'last_pymnt_amnt', 'last_pymnt_d', 'loan_amnt', 'loan_status', 'loan_status_binary', 'max_bal_bc', 'member_id', 'mo_sin_old_il_acct', 'mo_sin_old_rev_tl_op', 'mo_sin_rcnt_rev_tl_op', 'mo_sin_rcnt_tl', 'mort_acc', 'mths_since_last_delinq', 'mths_since_last_major_derog', 'mths_since_last_record', 'mths_since_rcnt_il', 'mths_since_recent_bc', 'mths_since_recent_bc_dlq', 'mths_since_recent_inq', 'mths_since_recent_revol_delinq', 'next_pymnt_d', 'num_accts_ever_120_pd', 'num_actv_bc_tl', 'num_actv_rev_tl', 'num_bc_sats', 'num_bc_tl', 'num_il_tl', 'num_op_rev_tl', 'num_rev_accts', 'num_rev_tl_bal_gt_0', 'num_sats', 'num_tl_120dpd_2m', 'num_tl_30dpd', 'num_tl_90g_dpd_24m', 'num_tl_op_past_12m', 'open_acc', 'open_acc_6m', 'open_act_il', 'open_il_12m', 'open_il_24m', 'open_rv_12m', 'open_rv_24m', 'orig_projected_additional_accrued_interest', 'out_prncp', 'out_prncp_inv', 'payment_plan_start_date', 'pct_tl_nvr_dlq', 'percent_bc_gt_75', 'policy_code', 'pub_rec', 'pub_rec_bankruptcies', 'purpose', 'pymnt_plan', 'recoveries', 'revol_bal', 'revol_bal_joint', 'revol_util', 'sec_app_chargeoff_within_12_mths', 'sec_app_collections_12_mths_ex_med', 'sec_app_earliest_cr_line', 'sec_app_fico_range_high', 'sec_app_fico_range_low', 'sec_app_inq_last_6mths', 'sec_app_mort_acc', 'sec_app_mths_since_last_major_derog', 'sec_app_num_rev_accts', 'sec_app_open_acc', 'sec_app_open_act_il', 'sec_app_revol_util', 'settlement_amount', 'settlement_date', 'settlement_percentage', 'settlement_status', 'settlement_term', 'sub_grade', 'tax_liens', 'term', 'title', 'tot_coll_amt', 'tot_cur_bal', 'tot_hi_cred_lim', 'total_acc', 'total_bal_ex_mort', 'total_bal_il', 'total_bc_limit', 'total_cu_tl', 'total_il_high_credit_limit', 'total_pymnt', 'total_pymnt_inv', 'total_rec_int', 'total_rec_late_fee', 'total_rec_prncp', 'total_rev_hi_lim', 'url', 'verification_status', 'verification_status_joint', 'zip_code']

Using information online and the best knowledge we have to retain columns that do not leak information into the future & are not irrelevant
- Things Lending Club knows at application / approval:
    - borrower info: income, employment, purpose, state
    - credit bureau info: FICO, delinquencies, utilisation, counts
    - loan terms: amount, term, interest rate, grade
    - origination date: issue_d

In [28]:
cols_to_keep = [
    # Response variable (loan status binary)
    "loan_status_binary",
    
    # Loan terms (known before issuing the loan)
    "loan_amnt",
    "term",
    "int_rate",
    "installment",
    "funded_amnt",
    "funded_amnt_inv",
    "grade",
    "sub_grade",
    "initial_list_status",
    "disbursement_method",
    
    # Borrower attributes (application)
    "emp_title",
    "emp_length",
    "home_ownership",
    "annual_inc",
    "verification_status",
    "purpose",
    "application_type",    
    "issue_d",
    
    # Credit bureau attributes at time of application
    "dti",
    "delinq_2yrs",
    "earliest_cr_line",
    "inq_last_6mths",
    "open_acc",
    "pub_rec",
    "revol_bal",
    "revol_util",
    "total_acc",
    "fico_range_low",
    "fico_range_high",
    'pymnt_plan',
    
    # Richer bureau attributes (still at application)
    "acc_open_past_24mths",
    "bc_open_to_buy",
    "bc_util",
    "chargeoff_within_12_mths",   # applicant’s past credit behaviour
    "collections_12_mths_ex_med",
    "delinq_amnt",
    "inq_fi",
    "inq_last_12m",
    "max_bal_bc",
    "mo_sin_old_il_acct",
    "mo_sin_old_rev_tl_op",
    "mo_sin_rcnt_rev_tl_op",
    "mo_sin_rcnt_tl",
    "mort_acc",
    "mths_since_last_delinq",
    "mths_since_last_major_derog",
    "mths_since_last_record",
    "mths_since_rcnt_il",
    "num_accts_ever_120_pd",
    "num_actv_bc_tl",
    "num_actv_rev_tl",
    "num_bc_sats",
    "num_bc_tl",
    "num_il_tl",
    "num_op_rev_tl",
    "num_rev_accts",
    "num_rev_tl_bal_gt_0",
    "num_sats",
    "num_tl_120dpd_2m",
    "num_tl_30dpd",
    "num_tl_90g_dpd_24m",
    "num_tl_op_past_12m",
    "open_acc_6m",
    "open_act_il",
    "open_il_12m",
    "open_il_24m",
    "open_rv_12m",
    "open_rv_24m",
    "pct_tl_nvr_dlq",
    "percent_bc_gt_75",
    "pub_rec_bankruptcies",
    "tax_liens",
    "tot_hi_cred_lim",
    "total_bal_ex_mort",
    "total_bal_il",
    "total_bc_limit",
    "total_cu_tl",
    "total_il_high_credit_limit",
]

In [29]:
cols_to_drop = [col for col in data.columns if col not in cols_to_keep]
print(cols_to_drop)
print(len(cols_to_drop))

['id', 'member_id', 'loan_status', 'url', 'desc', 'title', 'zip_code', 'addr_state', 'out_prncp', 'out_prncp_inv', 'total_pymnt', 'total_pymnt_inv', 'total_rec_prncp', 'total_rec_int', 'total_rec_late_fee', 'recoveries', 'collection_recovery_fee', 'last_pymnt_d', 'last_pymnt_amnt', 'next_pymnt_d', 'last_credit_pull_d', 'last_fico_range_high', 'last_fico_range_low', 'policy_code', 'annual_inc_joint', 'dti_joint', 'verification_status_joint', 'acc_now_delinq', 'tot_coll_amt', 'tot_cur_bal', 'il_util', 'all_util', 'total_rev_hi_lim', 'avg_cur_bal', 'mths_since_recent_bc', 'mths_since_recent_bc_dlq', 'mths_since_recent_inq', 'mths_since_recent_revol_delinq', 'revol_bal_joint', 'sec_app_fico_range_low', 'sec_app_fico_range_high', 'sec_app_earliest_cr_line', 'sec_app_inq_last_6mths', 'sec_app_mort_acc', 'sec_app_open_acc', 'sec_app_revol_util', 'sec_app_open_act_il', 'sec_app_num_rev_accts', 'sec_app_chargeoff_within_12_mths', 'sec_app_collections_12_mths_ex_med', 'sec_app_mths_since_last_major_derog', 'hardship_flag', 'hardship_type', 'hardship_reason', 'hardship_status', 'deferral_term', 'hardship_amount', 'hardship_start_date', 'hardship_end_date', 'payment_plan_start_date', 'hardship_length', 'hardship_dpd', 'hardship_loan_status', 'orig_projected_additional_accrued_interest', 'hardship_payoff_balance_amount', 'hardship_last_payment_amount', 'debt_settlement_flag', 'debt_settlement_flag_date', 'settlement_status', 'settlement_date', 'settlement_amount', 'settlement_percentage', 'settlement_term']
73

In [30]:
data.drop(labels = cols_to_drop, inplace = True, axis = 1)

In [31]:
data.shape

(99905, 79)

In [32]:
data.sample(10)

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,pymnt_plan,purpose,dti,delinq_2yrs,earliest_cr_line,fico_range_low,fico_range_high,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,collections_12_mths_ex_med,mths_since_last_major_derog,application_type,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,open_rv_12m,open_rv_24m,max_bal_bc,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,disbursement_method,loan_status_binary
644670,22000.00,22000.00,22000.00,36 months,7.97,689.10,A,A5,Network Engineer,10+ years,MORTGAGE,80000.00,Source Verified,Jul-2017,n,debt_consolidation,25.04,0.00,Nov-2002,810.00,814.00,0.00,NaN,NaN,10.00,0.00,0.00,0.00,21.00,w,0.00,NaN,Individual,0.00,7.00,0.00,1.00,15.00,73902.00,0.00,0.00,0.00,1.00,1.00,0.00,1.00,17600.00,0.00,0.00,0.00,159.00,165.00,55.00,15.00,4.00,0.00,0.00,0.00,1.00,1.00,13.00,2.00,4.00,0.00,10.00,0.00,0.00,0.00,0.00,100.00,0.00,0.00,0.00,232286.00,73902.00,17600.00,110186.00,Cash,1
1247009,4800.00,4800.00,4800.00,36 months,10.99,157.13,B,B3,Substance Abuse Counselor,10+ years,RENT,53000.00,Source Verified,Jul-2014,n,credit_card,19.18,1.00,May-2002,665.00,669.00,2.00,22.00,NaN,8.00,0.00,13166.00,49.10,12.00,f,0.00,NaN,Individual,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,2590.00,75.30,0.00,0.00,117.00,145.00,4.00,4.00,0.00,0.00,2.00,5.00,2.00,3.00,4.00,7.00,8.00,5.00,8.00,0.00,0.00,0.00,2.00,72.70,50.00,0.00,0.00,53862.00,31444.00,10500.00,27062.00,Cash,1
741244,13000.00,13000.00,13000.00,36 months,5.32,391.50,A,A1,sales specialist,2 years,RENT,53000.00,Verified,Apr-2016,n,debt_consolidation,31.02,0.00,Nov-1999,695.00,699.00,0.00,NaN,NaN,7.00,0.00,11012.00,88.10,32.00,f,0.00,NaN,Joint App,0.00,3.00,2.00,3.00,9.00,102639.00,0.00,1.00,3086.00,0.00,16.00,1.00,4.00,414.00,88.20,0.00,0.00,156.00,196.00,15.00,9.00,3.00,0.00,1.00,3.00,1.00,4.00,16.00,4.00,13.00,3.00,7.00,0.00,0.00,0.00,2.00,100.00,100.00,0.00,0.00,121113.00,113651.00,3500.00,108613.00,Cash,1
2082549,20000.00,20000.00,20000.00,60 months,12.62,451.19,C,C1,Deputy Prosecuting Attorney,2 years,RENT,70000.00,Not Verified,Nov-2017,n,debt_consolidation,18.67,0.00,Nov-2001,705.00,709.00,0.00,NaN,NaN,6.00,0.00,19380.00,83.50,42.00,w,0.00,NaN,Joint App,0.00,3.00,0.00,1.00,15.00,297490.00,0.00,1.00,13563.00,2.00,0.00,0.00,2.00,3820.00,83.50,0.00,0.00,142.00,192.00,20.00,15.00,0.00,0.00,3.00,3.00,3.00,4.00,36.00,3.00,6.00,3.00,6.00,0.00,0.00,0.00,0.00,100.00,100.00,0.00,0.00,290530.00,316870.00,23200.00,267330.00,Cash,1
842986,17000.00,17000.00,17000.00,60 months,18.94,440.43,D,D2,Bus driver/securiety gard,10+ years,MORTGAGE,46000.00,Source Verified,Jul-2018,n,debt_consolidation,12.55,0.00,Apr-2008,665.00,669.00,0.00,NaN,NaN,16.00,0.00,14177.00,33.20,23.00,w,0.00,NaN,Individual,0.00,0.00,0.00,0.00,NaN,0.00,0.00,4.00,3841.00,0.00,0.00,0.00,4.00,11282.00,50.90,0.00,0.00,NaN,123.00,13.00,13.00,0.00,0.00,5.00,12.00,7.00,9.00,0.00,16.00,23.00,12.00,16.00,0.00,0.00,0.00,0.00,100.00,42.90,0.00,0.00,42700.00,14177.00,23000.00,0.00,Cash,1
79374,6400.00,6400.00,6400.00,36 months,7.89,200.23,A,A5,Consultant,1 year,RENT,78000.00,Verified,Oct-2015,n,other,15.23,0.00,Aug-2003,725.00,729.00,0.00,NaN,NaN,10.00,0.00,8531.00,29.70,38.00,w,0.00,NaN,Individual,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.00,10491.00,40.70,0.00,0.00,146.00,129.00,16.00,12.00,0.00,0.00,3.00,4.00,3.00,6.00,26.00,7.00,12.00,4.00,10.00,0.00,0.00,0.00,1.00,100.00,66.70,0.00,0.00,104961.00,69057.00,17700.00,76261.00,Cash,1
1832506,10000.00,10000.00,10000.00,36 months,11.14,328.06,B,B2,Pioneer RESA,10+ years,MORTGAGE,85000.00,Source Verified,Jul-2013,n,credit_card,18.70,0.00,Jul-1976,700.00,704.00,1.00,69.00,NaN,18.00,0.00,25686.00,73.20,39.00,f,0.00,NaN,Individual,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.00,4615.00,65.00,0.00,0.00,178.00,287.00,4.00,4.00,3.00,0.00,6.00,12.00,6.00,10.00,14.00,14.00,21.00,12.00,17.00,0.00,0.00,0.00,2.00,97.00,66.70,0.00,0.00,233349.00,110635.00,13200.00,96945.00,Cash,1
362383,23675.00,23675.00,23675.00,36 months,19.52,874.07,E,E3,Clinical Content Developer,4 years,MORTGAGE,74000.00,Verified,Feb-2015,n,small_business,13.06,0.00,Mar-2001,685.00,689.00,1.00,NaN,NaN,8.00,0.00,21007.00,88.30,27.00,f,0.00,NaN,Individual,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.00,121.00,96.30,0.00,0.00,113.00,167.00,11.00,11.00,3.00,0.00,1.00,4.00,1.00,6.00,5.00,6.00,19.00,4.00,8.00,0.00,0.00,0.00,1.00,100.00,100.00,0.00,0.00,183955.00,30011.00,3300.00,17655.00,Cash,0
1345167,9900.00,9900.00,9900.00,36 months,16.24,349.23,C,C5,Sales/Tech,10+ years,RENT,60000.00,Not Verified,Jan-2014,n,debt_consolidation,13.34,0.00,Aug-2002,665.00,669.00,0.00,60.00,NaN,6.00,0.00,4178.00,78.80,14.00,w,0.00,68.00,Individual,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.00,140.00,93.00,0.00,0.00,137.00,123.00,8.00,8.00,0.00,0.00,1.00,4.00,1.00,3.00,7.00,4.00,7.00,4.00,6.00,0.00,0.00,0.00,2.00,100.00,100.00,0.00,0.00,29081.00,24591.00,2000.00,23781.00,Cash,0
1417192,8000.00,8000.00,8000.00,36 months,19.92,296.99,D,D3,technician,4 years,RENT,47404.00,Not Verified,Nov-2018,n,debt_consolidation,17.27,0.00,Nov-1986,670.00,674.00,0.00,NaN,NaN,6.00,0.00,8029.00,57.40,10.00,w,1.00,NaN,Individual,0.00,2.00,0.00,0.00,37.00,20479.00,0.00,0.00,0.00,0.00,2.00,0.00,0.00,NaN,NaN,0.00,0.00,384.00,80.00,37.00,37.00,0.00,0.00,0.00,4.00,0.00,0.00,5.00,4.00,5.00,4.00,6.00,0.00,0.00,0.00,0.00,100.00,NaN,0.00,0.00,44170.00,28508.00,0.00,30170.00,Cash,1

In [33]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 99905 entries, 392949 to 347653
Data columns (total 79 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   loan_amnt                    99905 non-null  float64
 1   funded_amnt                  99905 non-null  float64
 2   funded_amnt_inv              99905 non-null  float64
 3   term                         99905 non-null  object
 4   int_rate                     99905 non-null  float64
 5   installment                  99905 non-null  float64
 6   grade                        99905 non-null  object
 7   sub_grade                    99905 non-null  object
 8   emp_title                    92519 non-null  object
 9   emp_length                   93454 non-null  object
 10  home_ownership               99905 non-null  object
 11  annual_inc                   99905 non-null  float64
 12  verification_status          99905 non-null  object
 13  issue_d                      99905 non-null  object
 14  pymnt_plan                   99905 non-null  object
 15  purpose                      99905 non-null  object
 16  dti                          99825 non-null  float64
 17  delinq_2yrs                  99905 non-null  float64
 18  earliest_cr_line             99905 non-null  object
 19  fico_range_low               99905 non-null  float64
 20  fico_range_high              99905 non-null  float64
 21  inq_last_6mths               99905 non-null  float64
 22  mths_since_last_delinq       48789 non-null  float64
 23  mths_since_last_record       15978 non-null  float64
 24  open_acc                     99905 non-null  float64
 25  pub_rec                      99905 non-null  float64
 26  revol_bal                    99905 non-null  float64
 27  revol_util                   99843 non-null  float64
 28  total_acc                    99905 non-null  float64
 29  initial_list_status          99905 non-null  object
 30  collections_12_mths_ex_med   99903 non-null  float64
 31  mths_since_last_major_derog  25830 non-null  float64
 32  application_type             99905 non-null  object
 33  open_acc_6m                  61646 non-null  float64
 34  open_act_il                  61646 non-null  float64
 35  open_il_12m                  61646 non-null  float64
 36  open_il_24m                  61646 non-null  float64
 37  mths_since_rcnt_il           59729 non-null  float64
 38  total_bal_il                 61646 non-null  float64
 39  open_rv_12m                  61646 non-null  float64
 40  open_rv_24m                  61646 non-null  float64
 41  max_bal_bc                   61646 non-null  float64
 42  inq_fi                       61646 non-null  float64
 43  total_cu_tl                  61646 non-null  float64
 44  inq_last_12m                 61646 non-null  float64
 45  acc_open_past_24mths         97878 non-null  float64
 46  bc_open_to_buy               96763 non-null  float64
 47  bc_util                      96717 non-null  float64
 48  chargeoff_within_12_mths     99903 non-null  float64
 49  delinq_amnt                  99905 non-null  float64
 50  mo_sin_old_il_acct           94008 non-null  float64
 51  mo_sin_old_rev_tl_op         97015 non-null  float64
 52  mo_sin_rcnt_rev_tl_op        97015 non-null  float64
 53  mo_sin_rcnt_tl               97015 non-null  float64
 54  mort_acc                     97878 non-null  float64
 55  num_accts_ever_120_pd        97015 non-null  float64
 56  num_actv_bc_tl               97015 non-null  float64
 57  num_actv_rev_tl              97015 non-null  float64
 58  num_bc_sats                  97520 non-null  float64
 59  num_bc_tl                    97015 non-null  float64
 60  num_il_tl                    97015 non-null  float64
 61  num_op_rev_tl                97015 non-null  float64
 62  num_rev_accts                97015 non-null  float64
 63  num_rev_tl_bal_gt_0          97015 non-null  float64
 64  num_sats                     97520 non-null  float64
 65  num_tl_120dpd_2m             93271 non-null  float64
 66  num_tl_30dpd                 97015 non-null  float64
 67  num_tl_90g_dpd_24m           97015 non-null  float64
 68  num_tl_op_past_12m           97015 non-null  float64
 69  pct_tl_nvr_dlq               97010 non-null  float64
 70  percent_bc_gt_75             96741 non-null  float64
 71  pub_rec_bankruptcies         99874 non-null  float64
 72  tax_liens                    99904 non-null  float64
 73  tot_hi_cred_lim              97015 non-null  float64
 74  total_bal_ex_mort            97878 non-null  float64
 75  total_bc_limit               97878 non-null  float64
 76  total_il_high_credit_limit   97015 non-null  float64
 77  disbursement_method          99905 non-null  object
 78  loan_status_binary           99905 non-null  int64
dtypes: float64(64), int64(1), object(14)
memory usage: 61.0+ MB

In [34]:
data['term'] = np.where(data['term']==' 36 months', 36, 60)
data['issue_d'] = pd.to_datetime(data['issue_d'])
data['earliest_cr_line'] = pd.to_datetime(data['earliest_cr_line'])

/var/folders/tg/g161x0m50lxgx68hfwk_3qk80000gn/T/ipykernel_71924/3756829943.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data['issue_d'] = pd.to_datetime(data['issue_d'])
/var/folders/tg/g161x0m50lxgx68hfwk_3qk80000gn/T/ipykernel_71924/3756829943.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data['earliest_cr_line'] = pd.to_datetime(data['earliest_cr_line'])

In [35]:
data['emp_length'].unique()

array(['10+ years', nan, '4 years', '5 years', '8 years', '7 years',
       '2 years', '1 year', '< 1 year', '9 years', '6 years', '3 years'],
      dtype=object)

## Pre-processing

In [36]:
# Want to determine if columns are categorical 
def analyze_categorical_features(df, unique_value_threshold=50):
    """
    Identifies and counts categories for columns that are either
    of 'object' type or have fewer unique values than the specified threshold.

    Args:
        df (pd.DataFrame): The DataFrame to analyze.
        unique_value_threshold (int): Max number of unique values a column
                                      can have to be considered categorical.

    Returns:
        dict: A dictionary where keys are column names and values are 
              their unique category counts.
    """
    categorical_counts = {}
    
    # 1. Identify candidate columns
    for col in df.columns:
        # Check if column is object type (string)
        if df[col].dtype == 'object':
            # Strings are always treated as categorical candidates
            is_categorical = True
        
        # Check if column is numeric but has a small number of unique values
        elif df[col].nunique() < unique_value_threshold:
            is_categorical = True
            
        else:
            is_categorical = False
            
        # 2. Store the count if it's a categorical candidate
        if is_categorical:
            # Drop NA values before counting unique categories
            count = df[col].nunique(dropna=True)
            categorical_counts[col] = count
            
    # Optional: Print results for easy viewing
    print(f"Found {len(categorical_counts)} categorical columns/candidates (Threshold: < {unique_value_threshold} unique values).")
    print("-" * 50)
    for col, count in sorted(categorical_counts.items(), key=lambda item: item[1], reverse=True):
        print(f"{col:<30} | Categories: {count}")
            
    return categorical_counts

# Example Usage (assuming your DataFrame is named 'data'):
# cat_summary = analyze_categorical_features(data)

In [37]:
missing_pct = data.isnull().sum() / len(data) * 100
high_missing_cols = missing_pct[missing_pct > 50].sort_values(ascending=False)
print(high_missing_cols)
print(f"\nTotal number of high-missing columns: {len(high_missing_cols)}")

mths_since_last_record        84.01
mths_since_last_major_derog   74.15
mths_since_last_delinq        51.16
dtype: float64

Total number of high-missing columns: 3

In [38]:
for col in data.columns:
    if data[col].dtype==object:
        print(data[col].value_counts())

grade
B    29203
C    28902
A    18925
D    14424
E     6053
F     1844
G      554
Name: count, dtype: int64
sub_grade
C1    6516
B5    6234
B4    6105
C2    5767
C4    5745
C3    5741
B3    5690
B2    5645
B1    5529
C5    5133
A5    4677
A4    4034
A1    3781
D1    3566
D2    3352
A3    3226
A2    3207
D3    2924
D4    2544
D5    2038
E1    1485
E2    1404
E3    1146
E4    1024
E5     994
F1     584
F2     414
F3     333
F4     278
F5     235
G1     175
G2     112
G3     104
G4      87
G5      76
Name: count, dtype: int64
emp_title
Teacher                                        1750
Manager                                        1507
Owner                                           906
Registered Nurse                                694
Driver                                          685
Supervisor                                      654
RN                                              626
Sales                                           591
Project Manager                                 471
Office Manager                                  438
General Manager                                 410
Director                                        399
owner                                           375
President                                       365
Engineer                                        337
manager                                         328
teacher                                         295
Operations Manager                              271
Vice President                                  260
Accountant                                      255
driver                                          248
Administrative Assistant                        248
Attorney                                        246
Sales Manager                                   239
Nurse                                           237
Account Manager                                 203
Executive Assistant                             201
Analyst                                         200
Server                                          197
Store Manager                                   189
Truck Driver                                    188
Police Officer                                  188
Technician                                      187
Mechanic                                        179
sales                                           176
supervisor                                      169
Paralegal                                       168
Software Engineer                               159
Assistant Manager                               155
CEO                                             153
Program Manager                                 150
Supervisor                                      149
Controller                                      148
Principal                                       143
Foreman                                         143
Consultant                                      139
Branch Manager                                  139
Electrician                                     138
Truck driver                                    128
Customer Service                                126
Operator                                        123
Administrator                                   121
Professor                                       120
Account Executive                               119
Registered nurse                                118
Manager                                         115
Executive Director                              115
truck driver                                    113
Clerk                                           112
Bartender                                       110
Business Analyst                                108
IT Manager                                      107
LPN                                             106
Teacher                                         102
Partner                                          98
Director of Operations                           95
Cashier                                          95
Physician                                        92
Realtor                                          88
Financial Advisor                                87
Secretary                                        86
Legal Assistant                                  86
Superintendent                                   86
Maintenance                                      85
mechanic                                         84
Bookkeeper                                       84
CNA                                              81
Cook                                             81
Accounting Manager                               81
District Manager                                 81
registered nurse                                 81
Financial Analyst                                80
Owner                                            80
Service Manager                                  79
Laborer                                          79
Software Developer                               79
Instructor                                       79
Dispatcher                                       76
Pharmacist                                       76
Property Manager                                 76
Machine Operator                                 74
Officer                                          73
Welder                                           73
Senior Project Manager                           72
Machinist                                        72
MANAGER                                          71
Business Manager                                 70
Assistant Principal                              70
Associate                                        70
Nurse Practitioner                               68
Social Worker                                    67
VP                                               67
Buyer                                            66
Finance Manager                                  65
Counselor                                        65
Regional Manager                                 65
Office manager                                   64
Store manager                                    64
Tech                                             64
Underwriter                                      64
electrician                                      64
Loan Officer                                     63
CFO                                              63
Production Manager                               62
Correctional Officer                             62
Rn                                               62
Senior Manager                                   62
Respiratory Therapist                            61
Firefighter                                      61
Pastor                                           60
Network Engineer                                 60
Case Manager                                     60
Driver                                           59
Technician                                       59
Receptionist                                     59
Superintendent                                   58
nurse                                            58
Auditor                                          57
IT Specialist                                    57
Managing Director                                57
Security Officer                                 56
Vice President                                   56
Sales Representative                             56
General manager                                  55
OWNER                                            55
Police officer                                   55
Sales Associate                                  55
Product Manager                                  55
Chef                                             54
Management                                       54
general manager                                  54
Pilot                                            54
Coordinator                                      54
Flight Attendant                                 53
Maintenance                                      53
Systems Engineer                                 53
Marketing Manager                                53
Medical Assistant                                52
Senior Accountant                                52
Sales manager                                    52
Designer                                         52
Assistant Professor                              51
Deputy                                           51
CSR                                              51
Carpenter                                        51
Agent                                            51
Captain                                          51
HR Manager                                       50
Senior Consultant                                49
Investigator                                     49
office manager                                   49
Recruiter                                        48
maintenance                                      48
Director of Sales                                48
Area Manager                                     48
Staff Accountant                                 47
Team Leader                                      47
Project Engineer                                 47
technician                                       47
Caregiver                                        47
president                                        47
Legal Secretary                                  46
Sales                                            46
Regional Sales Manager                           46
clerk                                            46
Assistant Store Manager                          46
Accounting                                       46
server                                           46
IT                                               46
GM                                               45
COO                                              45
Estimator                                        44
Bus Driver                                       44
Sales Rep                                        44
Assistant manager                                44
Physical Therapist                               44
Electrician                                      44
machinist                                        44
Registered Nurse                                 44
Senior Software Engineer                         43
Teller                                           43
Warehouse Manager                                43
Personal Banker                                  43
Systems Administrator                            43
Production                                       43
Associate Professor                              43
Program Analyst                                  43
Conductor                                        43
store manager                                    43
Territory Manager                                43
Senior Engineer                                  42
LVN                                              42
engineer                                         42
Service Technician                               42
Senior Vice President                            42
foreman                                          42
Custodian                                        41
Graphic Designer                                 41
laborer                                          41
Courier                                          41
Pharmacy Technician                              41
Human Resources Manager                          41
Educator                                         41
Customer Service Representative                  41
IT Director                                      41
Plant Manager                                    40
Systems Analyst                                  40
Security                                         40
Human Resources                                  40
operator                                         40
Department Manager                               40
Sales Consultant                                 40
Painter                                          39
Inspector                                        39
Electrical Engineer                              38
Engineering Manager                              38
Warehouse                                        38
Sales Executive                                  38
Customer Service Manager                         38
Project Coordinator                              38
Admin                                            38
Administrative Assistant                         38
Senior Associate                                 38
police officer                                   38
Program Director                                 37
Maintenance Supervisor                           37
Banker                                           37
Deputy Sheriff                                   37
Program Coordinator                              37
Marketing                                        37
project manager                                  36
Customer Service Rep                             36
Physician Assistant                              36
Project manager                                  36
cashier                                          36
Truck driver                                     35
Team Lead                                        35
Associate Director                               35
Network Administrator                            35
carpenter                                        35
Bus Operator                                     35
Therapist                                        34
Machine operator                                 34
Assistant Director                               34
Dental Hygienist                                 34
Plumber                                          34
sales manager                                    34
Assembler                                        34
cook                                             34
IT Project Manager                               34
SUPERVISOR                                       34
Administration                                   34
Quality Engineer                                 33
Sergeant                                         33
Operations Supervisor                            33
Marketing Director                               33
Assistant manager                                33
Salesman                                         33
System Administrator                             33
Sales Director                                   33
Librarian                                        32
Administrative                                   32
OFFICE MANAGER                                   32
Sales Engineer                                   32
Insurance Agent                                  32
Executive Chef                                   32
Web Developer                                    32
Business Development Manager                     32
Operations                                       31
Dental Assistant                                 31
Delivery Driver                                  31
Trainer                                          31
Office Assistant                                 31
Operator                                         31
welder                                           31
Purchasing Manager                               31
Claims Adjuster                                  30
Director of Nursing                              30
President                                        30
Senior Analyst                                   30
Director                                         29
Truck Driver                                     29
DRIVER                                           29
Customer service                                 29
customer service                                 29
Detective                                        29
Specialist                                       29
Stylist                                          29
machine operator                                 29
Lieutenant                                       29
Inside Sales                                     29
Probation Officer                                29
Quality Manager                                  28
custodian                                        28
Mechanical Engineer                              28
Corrections Officer                              28
Letter Carrier                                   28
operations manager                               28
Dentist                                          28
System Analyst                                   28
Medical assistant                                28
Labor                                            28
Special Education Teacher                        28
Customer service                                 28
REGISTERED NURSE                                 28
Teacher/Coach                                    27
Senior Financial Analyst                         27
TEACHER                                          27
Owner/Operator                                   27
bus driver                                       27
Service Tech                                     27
tech                                             27
Occupational Therapist                           27
Broker                                           26
Registered nurse                                 26
Sr. Manager                                      26
letter carrier                                   26
Paramedic                                        26
Forman                                           26
Director of Marketing                            26
Executive Vice President                         26
Police officer                                   26
Bartender                                        26
Accounts Payable                                 26
Operations manager                               26
Nurse Manager                                    25
Carrier                                          25
HR Specialist                                    25
Medical Technologist                             25
Parts Manager                                    25
Data Analyst                                     25
Programmer                                       25
General manager                                  25
Construction Manager                             25
Dealer                                           25
Foreman                                          25
Senior Account Manager                           25
accountant                                       25
PRESIDENT                                        25
CPA                                              25
Managing Partner                                 24
cna                                              24
Lab Tech                                         24
Office Manager                                   24
Nanny                                            24
Dental assistant                                 24
HR Generalist                                    24
Budget Analyst                                   24
Maintenance Technician                           24
Lpn                                              24
Mechanic                                         24
School Counselor                                 24
Relationship Manager                             24
physician                                        24
Installer                                        24
Machine operator                                 24
rn                                               23
US Army                                          23
Creative Director                                23
Assistant Manager                                23
Assistant Vice President                         23
Housekeeper                                      23
Programmer Analyst                               23
Manufacturing Engineer                           23

In [ ]:
# removing columns with low information (almost to fully constant values)
data = data.drop(columns=['pymnt_plan', 'application_type', 'disbursement_method'])
data.shape

(99905, 76)